services:
  - type: web
    name: rantau
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: rantau-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
